(part "S2751-46R"
    (packageRef "S275146R")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "220")
    (property "Manufacturer_Name" "Harwin")
    (property "Manufacturer_Part_Number" "S2751-46R")
    (property "Mouser_Part_Number" "855-S2751-46R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Harwin/S2751-46R?qs=DaxoyN%2FvrebM3VuuS3MPNA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Circuit Board Hardware - PCB SMT Mini Test Terminal, Reel")
    (property "Datasheet_Link" "https://cdn.harwin.com/pdfs/S2751R.pdf")
    (property "symbolName1" "S2751-46R")
)
